spec:
  replicas: 1
  template:
    spec:
      containers:
      - imagePullPolicy: Always
        env:
        - name: JAVA_OPTS_MEM
          value: -Xmx74M -XX:MaxMetaspaceSize=80M -Xss366K
        - name: SPRING_OPTS
          value: >-
            --server.port=8080 
            --spring.profiles.active=k8
            --eureka.client.serviceUrl.defaultZone=http://startup-msa-discovery-server/eureka/
        ports:
        - containerPort: 8080
          name: http-service
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          initialDelaySeconds: 90
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          timeoutSeconds: 5
          initialDelaySeconds: 480
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - mountPath: "/var/log/sb-app/"
          name: container-log
      volumes:
      - name: container-log
        emptyDir: {}
