eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: host.docker.internal
    preferIpAddress: false
    
      